# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create report file
        run: |
          auth="$(curl https://www.ptsplus.tv/"$(curl https://www.ptsplus.tv/ | grep -ioE 'main.[a-zA-Z0-9]+.bundle.js')" | grep -oE 'authorization:"([A-Za-z0-9]+)"')"
          replacement='"authorization"'
          auth=${auth/authorization/$replacement}
          body="{
              ${auth},
              \"loginType\": 1,
              \"password\": \"987@@Pts\",
              \"username\": \"vnijbdeavqvatpssxp@mhzayt.online\"
            }"
          token="$(curl --location --request POST 'https://www.ptsplus.tv/api/login' --header 'Content-Type: application/json' --data-raw "$body" |  grep -oE '"[a-zA-Z0-9-]+",')"
          token=${token//\"/}
          token=${token//,/}
          echo $token > ptsdrama.html

      - name: Commit report
        run: |
          git config --global user.name 'linkedintestapp2020'
          git config --global user.email 'linkedintestapp2020@users.noreply.github.com'
          git add ptsdrama.html
          git commit -am "Automated ptsdrama"
          git push
